# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_STM32_DCMI) += stm32-dcmi.o
stm32-dma2d-objs := dma2d/dma2d.o dma2d/dma2d-hw.o
obj-$(CONFIG_VIDEO_STM32_DMA2D) += stm32-dma2d.o
stm32-jpeg-objs := jpeg/stm-jpeg.o dma2d/stm-jpeg-hw.o
obj-$(CONFIG_VIDEO_STM32_JPEG) += stm32-jpeg.o
